############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################


############################################################
# +------------------------------------------------------+ #
# |                       DRank                          | #
# +------------------------------------------------------+ #
############################################################

chat:
  format: "%rank%%player% &7: &f%message%"